server:
  port: 8080
  servlet:
    context-path: /api/v1/cache/client

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: Cache-Client

logging:
  level:
    io.lettuce: debug

app:
  cache:
    configByName:
      "exchanges":
        timeToLive: 1200s
      "countries":
        timeToLive: 10m
      "country:exist":
        timeToLive: 5m
